clojure-emacs/clojure-ts-mode

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
Fixes #30
`clojure-ts-toplevel-inside-comment-form` is the equivalent to `clojure-toplevel-inside-comment-form` in clojure-mode. Defaults to `nil` so no change in behavior by default.
This change makes use of [`treesit-defun-type-regexp`s ability to use `(REGEXP . PRED)`](https://github.com/emacs-mirror/emacs/blob/a4587646fabf2b7f0cb19a7e0bee090f9106a73a/lisp/treesit.el#L2225-L2229) cons cells to reject `comment` as a defun if `clojure-ts-toplevel-inside-comment-form` is enabled.
> Add clojure-ts-toplevel-inside-comment-form

- CHANGELOG.md
- clojure-ts-mode.el
Consider this clojure code, `|` indicating the point position
```clojure
(ns my.app)
(defn foo []
(+ 1 1))
foo|
"another sexp"
(defn bar []
(+ 2 1))
```
Without this change, `beginning-of-defun` would move point before the `(defn foo,,,)` as the symbol literal `foo` is not considered as a valid defun.
With this change, all clojure sexps will be considered as defuns, so `beginning-of-defun` moves point before `foo`, which I would consider as the expected behavior.
Similar for `cider-eval-defun-at-point`: At the point position indicated in the example without this change the `(defn bar,,,)` form is evaluated. With this change, `foo` is evaluated, which I also would consider the expected behavior.
> Consider all clojure sexps as defuns

- CHANGELOG.md
- clojure-ts-mode.el
Fix all the errors from flycheck.
This contains a breaking change with the derived mode vars being renamed.
- `clojurescript-ts-mode` -> `clojure-ts-clojurescript-mode`
- `clojurec-ts-mode` -> `clojure-ts-clojurec-mode`
- `clojure-dart-ts-mode` -> `clojure-ts-clojuredart-mode`
- `clojure-jank-ts-mode` -> `clojure-ts-jank-mode`
> Fix flycheck errors

- .github/workflows/lint-emacs.yml
- .gitignore
- Eldev
- Makefile
- clojure-ts-mode.el
- test/clojure-ts-mode-util-test.el
- Setup Eldev and Makefile.
- Add 1 test with buttercup.
- Add github actions for tests and linting.
- Fix indentation and check-declare errors from Eldev.
> Setup Eldev, Makefile, Tests and Update Github Actions

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-util-test.el
- test/utils/test-helper.el
- Add support for `in-ns` when finding namespace.
- Remove text property of ns.
- Add a couple of test helpers and find-ns tests equivalent to `clojure-mode`.
> Update clojure-ts-find-ns to support `in-ns` and Add tests

- README.md
I noticed that the readme was out of date for CIDER.
Thanks!
> Update README.md to show CIDER and inf-clojure status

- CHANGELOG.md
- clojure-ts-mode.el
> Fix missing `comment-add` variable in `clojure-ts-mode-variables`

- CHANGELOG.md
- clojure-ts-mode.el
Emacs 30 defines the function `derived-mode-add-parents` that is used for the built-in *-ts-mode, this will make `(provided-mode-derived-p 'clojure-ts-mode 'clojure-mode)` return true just like other treesit major modes.
> Let clojure-ts-mode derive from clojure-mode for Emacs 30+

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-imenu-test.el
Partly addresses #42
Also comes with some basic tests. 
Extracted from https://github.com/clojure-emacs/clojure-ts-mode/pull/43 as discussed there in the comments.
> Fix definitions with metadata not being index by imenu

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
- test/clojure-ts-mode-imenu-test.el
- test/samples/test.clj
Partly addresses #42 
Extracted from #43 as discussed there.
> Fix font locking of defintions with metadata

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/indentation.clj
Fixes an error where quoted functions would not align correctly with semantic indentation. Adds an example to the test sample.
Thanks!
> Fix semantic indentation of quoted functions

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-fill-paragraph-test.el
> Add custom `fill-paragraph` function to respect docstrings

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
Thanks!
---
I would like to introduce a new customization option to disable inline markdown. 
After working for some time with `clojure-ts-mode` on relatively big project I noticed some problems with it. Markdown syntax highlighting is not accurate (note closing backtick has different color in different docstrings):
Also having it enabled sometimes introduces memory leaks. Emacs hangs and consumes all available RAM. Unfortunately I couldn't figure out a reliable recipe to reproduce the memory leak.
> Add customization option to disable markdown syntax highlighting

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
If list thing is defined, Emacs 31 will set a few options automatically to improve navigation by lists/sexp etc.
Big thanks for the patch to Juri Linkov <juri@linkov.net>.
Thanks!
> Define list thing to improve navigation in Emacs 31

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
Closes #63 
Naming of defcustom / commands open to change, if alright I can go ahead and edit the changelog/Readme
Thanks!
> Add defcustom for major-mode remapping

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
- test/samples/test.clj
Fix a few issues with syntax highlighting I discovered.
Before:
After:
There were failing tests in `clojure-ts-mode-font-lock-test.el` (not sure how did they pass CI before), those are fixed now.
Thanks!
> Improve syntax highlighting

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/indentation.clj
- test/test-helper.el
> Improve semantic indentation rules to be more consistent with cljfmt

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/indentation.clj
- Collection elements (except of lists) are properly indented.
- Body of special forms when the entire form has metadata is properly indented.
- Additionally fix syntax highlighting of special forms when the entire form has metadata.
Close #61 
Before:
Here besides incorrect indentation, `if` is not highlighted properly:
After:
Thanks!
> Fix some issues with indentation for items with metadata

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
This PR introduces `clojure-ts-get-indent-function` variable, which can be set by CIDER as:
```emacs-lisp
(setq-local clojure-ts-get-indent-function #'cider--get-symbol-indent)
```
to enable dynamic indentation based on `:style/indent` metadata. Currently it supports only first level, so `{:style/indent 1}` and `{:style/indent [1 [[:defn]] :form]}` are both translated to `(:block 1)` rule.
I haven't added anything to README, because it's internal change, similar function is not mentioned in `clojure-mode` readme as well.
Thanks!
> Basic support for dynamic indentation

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
When I started testing it with CIDER I realized that we have to pass fully qualified symbol name to `cider--get-symbol-indent`, otherwise it won't resolve it and won't return indentation metadata.
Thanks!
> Pass fully qualified symbol to clojure-ts-get-indent-function

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
I've noticed that reindenting big file is pretty slow, profiler report indicated that the bottleneck is the calculation of combined indentation rules from default settings and user customizations:
```emacs-lisp
(seq-union (or rules clojure-ts-semantic-indent-rules)
clojure-ts--semantic-indent-rules-defaults
(lambda (e1 e2) (equal (car e1) (car e2))))
```
this is called every time we need to calculate indentation for a single line. 
This PR introduces buffer local variable `clojure-ts--semantic-indent-rules-cache` which stores pre-calculated rules. This variable is set when `clojure-ts-mode` is activated and updated every time when `clojure-ts-semantic-indent-rules` is updated or file local variables are updated (in case when indentation rules are defined in `.dir-locals.el` for example. …
> Improve performance of semantic indentation by caching rules

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-imenu-test.el
- test/samples/spec.clj
Close #74 
I decided to make it more generic and add support for all def forms with keywords. It might be useful for other libraries (like [spec-tools](https://github.com/metosin/spec-tools) for eample).
Before:
After:
I use `imenu-flatten 'prefix` option to display all items on the screenshots.
Thanks!
> Add imenu support for keyword definitions

- CHANGELOG.md
- Eldev
- clojure-ts-mode.el
- test/samples/docstrings.clj
Follow up https://github.com/clojure-emacs/clojure-ts-mode/pull/78
- package-lint is disabled
- added more queries for markdown syntax in the docstrings
Thanks!
> Improve markdown highlighting in the docstrings

- CHANGELOG.md
- clojure-ts-mode.el
Many thanks to Juri Linkov <juri@linkov.net> for his assistance.
Close #60 
- Use local inline-markdown parsers for each docstring to avoid fontification of unrelated Clojure code.
- Define sexp "things" for inline markdown to improve navigation inside of the docstrings.
Thanks!
> Fix issue with fontification when markdown-inline is enabled

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/align.clj
First part for #16 
The code is adapted from `clojure-mode`, but I used `treesit-*` API wherever it was appropriate and possible. The most difficult part is dealing with metadata, I left comments describing how it works.
The function is bound to `C-c SPC` in `clojure-ts-mode-map`, similar to `clojure-mode`.
I also disabled `tab-indent-mode` by default for `clojure-ts-mode`, similar to `clojure-mode`, otherwise it tries to use tabs for alignment and sometimes it looks ugly.
Thanks!
> Implement `clojure-ts-align`

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/align.clj
Close #16 
I copied all related tests from `clojure-mode` with one exception. `should handle incomplete sexps` won't work, because syntax tree will be broken.
I also found a few issues in the `clojure-ts-align` after running full `clojure-mode` test suite. All the issues are fixed now.
Thanks!
> Add support for automatic aligning forms

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/samples/outline.clj
> Support 2 variants of integration with `outline-minor-mode`

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
- test/clojure-ts-mode-refactor-threading-test.el
- test/clojure-ts-mode-util-test.el
- test/samples/refactoring.clj
- test/test-helper.el
The new commands work the same as in `clojure-mode` with one improvement (hopefully):
In `clojure-mode` unwinding form `(-> foo bar)` would produce `(-> (bar foo))`, so you need to run unwind command one more time to get rid of threading macro. In `clojure-ts-mode` it will produce `(bar foo)` immediately. Because of that I had to adapt tests from `clojure-mode` a little bit.
Thanks!
> Add unwind refactoring commands

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-refactor-threading-test.el
- test/samples/indentation.clj
- test/samples/refactoring.clj
All related tests from `clojure-mode` pass except of those which "unjoin" lines, in `clojure-mode` it's implemented via text properties and doesn't work for the same expression after restarting Emacs. If it's an important feature, we can deal with that later.
I also fixed a couple of small issues with indentation and aligning forms.
Thanks!
> Introduce threading refactoring commands

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-cycling-test.el
- test/samples/refactoring.clj
> Introduce cycle privacy refactoring command

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-cycling-test.el
> Introduce `clojure-ts-toggle-keyword-string`

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-convert-collection-test.el
- test/samples/refactoring.clj
> Introduce commands to convert collection type

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-refactor-add-arity-test.el
- test/samples/refactoring.clj
- test/test-helper.el
> Introduce `clojure-ts-add-arity` refactoring command

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-indentation-test.el
- test/samples/align.clj
- test/samples/refactoring.clj
- `clojure-ts-align` wasn't working if the expression has ignored forms (prefixed with `#_`)
- namespaced maps were not indented properly and were not supported by `clojure-ts-align`.
Thanks!
> Better handling of namespaced maps + bugfixes for `clojure-ts-align`

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
- test/clojure-ts-mode-refactor-add-arity-test.el
- test/samples/refactoring.clj
- Highlight function name with `font-lock-function-name` face
- Support of `clojure-ts-add-arity` command
Thanks!
> Improve support of extend-protocol forms

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- doc/design.md
- test/clojure-ts-mode-refactor-threading-test.el
- test/samples/indentation.clj
- test/samples/navigation.clj
Following the https://github.com/sogaiu/tree-sitter-clojure/issues/65 discussion.
This PR contains a set of commit that accumulated while we were discussing changes in the grammar.
- Update queries to work with the new grammar. Queries are also improved to better skip comments and metadata nodes. Added support for some missing earlier forms (like `definterface`, `extend-type` etc).
- Better matching for docstrings for indentation and fill-paragraph function. Instead of defining custom functions we re-use docstring query now and check if node at point matches it.
- Fixed a minor bugs in `clojure-ts-align` + slight performance optimization by pre-compiling the query.
- Fixed a minor bug in `clojure-ts-unwind`.
This includes the changes from #98, so if this one is merged, I'll close the …
> Switch to experimental Clojure grammar

- doc/design.md
I don't understand what should be written in the last section "Semantic Interpretation in clojure-ts-mode". The example of syntax highlighting exists in the "Syntax highlighting" section.
> Add "Indentation" section to the design documentation

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/samples/embed.cljs
- test/samples/native.jank
Close #23 
ClojureScript:
Jank:
Thanks!
> Support syntax highlighting for embedded JS and C++

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-font-lock-test.el
Partially (or fully?) addresses #15 
In this PR I only added `clojure-ts-extra-def-forms` variable. I think we can add low-level customization if there is a request for that. For now dynamic font-lock from CIDER and this variable should cover most of the users needs.
Thanks!
> Introduce `clojure-ts-extra-def-forms` customization

- CHANGELOG.md
- README.md
- clojure-ts-mode.el
- test/clojure-ts-mode-completion.el
- test/samples/completion.clj
> Introduce `clojure-ts-completion-at-point-function`

- CHANGELOG.md
- clojure-ts-mode.el
We should use add-hook instead of add-to-list in order to set it only for clojure-ts-mode buffers.
Thanks!
> Set `clojure-ts-completion-at-point-function` locally

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-completion.el
- test/samples/completion.clj
Completions for:
- namespace aliases required with `:as`
- imported functions required with `:refer`
- imported Java classes
Following up https://github.com/clojure-emacs/clojure-ts-mode/pull/114#issuecomment-2993330689
Thanks!
> Extend completion to complete ns aliases and required symbols

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-util-test.el
- test/samples/deps-project/deps.edn
- test/samples/deps-project/src/clj/hello-clj/world.clj
- test/samples/deps-project/src/clj/hello/world.clj
- test/samples/refactoring.clj
- Add project helper functions.
- Add a few defcustom's
- Add ns helper functions.
NOTE: clojure-ts-sort-ns is not implemented, I think we should try to leverage Tree-sitter for that somehow, so I need more time to think about the implementation.
#117 
Thanks!
> Add some ns manipulation functions from clojure-mode

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-refactor-add-arity-test.el
- test/samples/refactoring.clj
The initial implementation only worked for a single expression body.
Thanks!
> Fix `clojure-ts-add-arity` bug when body has more than one expression

- CHANGELOG.md
- clojure-ts-mode.el
- test/clojure-ts-mode-imenu-test.el
> Fix a bug when vars with metadata were not listed in imenu
